"""Pydantic schemas"""

from app.schemas.coloring_book_template import (
    ColoringBookTemplateCreate,
    ColoringBookTemplateFilters,
    ColoringBookTemplateListItem,
    ColoringBookTemplateResponse,
    ColoringBookTemplateUpdate,
)
from app.schemas.generated_book import (
    BookGenerationCreate,
    BookGenerationResponse,
    BookPage,
    ChildInfo,
    GeneratedBookFilters,
    GeneratedBookListItem,
    GeneratedBookResponse,
    GeneratedBookUpdate,
    GenerationErrorDetail,
    GenerationStatusCancelled,
    GenerationStatusCompleted,
    GenerationStatusFailed,
    GenerationStatusProcessing,
    GenerationStatusQueued,
    GenerationStepStatus,
    PhotoToColoringGenerationCreate,
    TemplateInfo,
    ThemeBasedGenerationCreate,
)
from app.schemas.generation_config import (
    GenerationConfigCreate,
    GenerationConfigFilters,
    GenerationConfigListItem,
    GenerationConfigResponse,
    GenerationConfigUpdate,
    PublicThemeItem,
    ThemeConfigData,
    ThemeCreate,
    ThemeUpdate,
)
from app.schemas.story_book_template import (
    StoryBookTemplateCreate,
    StoryBookTemplateFilters,
    StoryBookTemplateListItem,
    StoryBookTemplateResponse,
    StoryBookTemplateSeriesInfo,
    StoryBookTemplateUpdate,
)
from app.schemas.user import (
    AccountDeletionRequest,
    AddressCreate,
    AddressListResponse,
    AddressResponse,
    AddressUpdate,
    AvatarUploadResponse,
    ChildProfileCreate,
    ChildProfileListResponse,
    ChildProfileResponse,
    ChildProfileUpdate,
    UserCreate,
    UserProfileResponse,
    UserUpdate,
)

__all__ = [
    # Story Book schemas
    "StoryBookTemplateCreate",
    "StoryBookTemplateUpdate",
    "StoryBookTemplateResponse",
    "StoryBookTemplateListItem",
    "StoryBookTemplateFilters",
    "StoryBookTemplateSeriesInfo",
    # Coloring Book schemas
    "ColoringBookTemplateCreate",
    "ColoringBookTemplateUpdate",
    "ColoringBookTemplateResponse",
    "ColoringBookTemplateListItem",
    "ColoringBookTemplateFilters",
    # Generated Book schemas
    "BookGenerationCreate",
    "BookGenerationResponse",
    "BookPage",
    "ChildInfo",
    "GeneratedBookFilters",
    "GeneratedBookListItem",
    "GeneratedBookResponse",
    "GeneratedBookUpdate",
    "GenerationErrorDetail",
    "GenerationStatusCancelled",
    "GenerationStatusCompleted",
    "GenerationStatusFailed",
    "GenerationStatusProcessing",
    "GenerationStatusQueued",
    "GenerationStepStatus",
    "PhotoToColoringGenerationCreate",
    "TemplateInfo",
    "ThemeBasedGenerationCreate",
    # Generation Config schemas
    "GenerationConfigCreate",
    "GenerationConfigFilters",
    "GenerationConfigListItem",
    "GenerationConfigResponse",
    "GenerationConfigUpdate",
    "PublicThemeItem",
    "ThemeConfigData",
    "ThemeCreate",
    "ThemeUpdate",
    # User schemas
    "AccountDeletionRequest",
    "AddressCreate",
    "AddressListResponse",
    "AddressResponse",
    "AddressUpdate",
    "AvatarUploadResponse",
    "ChildProfileCreate",
    "ChildProfileListResponse",
    "ChildProfileResponse",
    "ChildProfileUpdate",
    "UserCreate",
    "UserProfileResponse",
    "UserUpdate",
]
