# Alembic Migration Script Template
# This is the default template for new migrations

"""Initial migration - add book_templates table

Revision ID: 6605ff3f90bc
Revises: 
Create Date: 2026-02-14 19:51:42.725931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6605ff3f90bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_templates',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('template_type', sa.String(length=20), nullable=False),
    sa.Column('book_type', sa.String(length=20), nullable=True),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('book_number', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=False),
    sa.Column('preview_images', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('learning_outcomes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('customization_options', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('total_generated', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("age_group IN ('0-2', '3-5', '6-8', '9-12')", name='check_age_group'),
    sa.CheckConstraint("book_type IN ('single', 'series') OR book_type IS NULL", name='check_book_type'),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard') OR difficulty IS NULL", name='check_difficulty'),
    sa.CheckConstraint("template_type IN ('story_book', 'coloring_book')", name='check_template_type'),
    sa.CheckConstraint('price >= 0', name='check_price_positive'),
    sa.CheckConstraint('total_pages > 0', name='check_total_pages_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_templates_active_published', 'book_templates', ['is_active', 'is_published'], unique=False)
    op.create_index('idx_templates_search', 'book_templates', [sa.literal_column("to_tsvector('english', title || ' ' || description)")], unique=False, postgresql_using='gin')
    op.create_index('idx_templates_series', 'book_templates', ['series_id', 'book_number'], unique=False)
    op.create_index('idx_templates_tags', 'book_templates', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('idx_templates_type_genre', 'book_templates', ['template_type', 'genre'], unique=False)
    op.create_index(op.f('ix_book_templates_age_group'), 'book_templates', ['age_group'], unique=False)
    op.create_index(op.f('ix_book_templates_genre'), 'book_templates', ['genre'], unique=False)
    op.create_index(op.f('ix_book_templates_is_active'), 'book_templates', ['is_active'], unique=False)
    op.create_index(op.f('ix_book_templates_is_published'), 'book_templates', ['is_published'], unique=False)
    op.create_index(op.f('ix_book_templates_price'), 'book_templates', ['price'], unique=False)
    op.create_index(op.f('ix_book_templates_series_id'), 'book_templates', ['series_id'], unique=False)
    op.create_index(op.f('ix_book_templates_template_type'), 'book_templates', ['template_type'], unique=False)
    op.create_index(op.f('ix_book_templates_title'), 'book_templates', ['title'], unique=False)
    op.create_table('generated_books',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('child_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['book_templates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_books_template_id'), 'generated_books', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_books_template_id'), table_name='generated_books')
    op.drop_table('generated_books')
    op.drop_index(op.f('ix_book_templates_title'), table_name='book_templates')
    op.drop_index(op.f('ix_book_templates_template_type'), table_name='book_templates')
    op.drop_index(op.f('ix_book_templates_series_id'), table_name='book_templates')
    op.drop_index(op.f('ix_book_templates_price'), table_name='book_templates')
    op.drop_index(op.f('ix_book_templates_is_published'), table_name='book_templates')
    op.drop_index(op.f('ix_book_templates_is_active'), table_name='book_templates')
    op.drop_index(op.f('ix_book_templates_genre'), table_name='book_templates')
    op.drop_index(op.f('ix_book_templates_age_group'), table_name='book_templates')
    op.drop_index('idx_templates_type_genre', table_name='book_templates')
    op.drop_index('idx_templates_tags', table_name='book_templates', postgresql_using='gin')
    op.drop_index('idx_templates_series', table_name='book_templates')
    op.drop_index('idx_templates_search', table_name='book_templates', postgresql_using='gin')
    op.drop_index('idx_templates_active_published', table_name='book_templates')
    op.drop_table('book_templates')
    # ### end Alembic commands ###
